# Generated by Django 2.2.2 on 2019-07-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0003_csvfile_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfile',
            old_name='file',
            new_name='upload',
        ),
    ]
