# Generated by Django 2.2.2 on 2019-07-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_auto_20190703_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='user_filename',
            field=models.CharField(default='', max_length=3),
        ),
    ]
