# Generated by Django 2.2.2 on 2019-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0006_auto_20190703_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='user_filename',
            field=models.CharField(default='', max_length=3),
        ),
    ]
