# Generated by Django 2.2.2 on 2019-07-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0009_auto_20190703_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfile',
            old_name='upload',
            new_name='file',
        ),
    ]
