# Generated by Django 2.2.2 on 2019-07-05 14:30

from django.db import migrations, models
import fit.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0010_auto_20190703_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('user_filename', models.CharField(default='', max_length=255)),
                ('file', models.FileField(upload_to=fit.utils.unique_file_path)),
            ],
        ),
        migrations.DeleteModel(
            name='CsvFile',
        ),
    ]
