# Generated by Django 2.2.2 on 2019-07-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0011_auto_20190705_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CsvUpload',
            new_name='Upload',
        ),
    ]
