# Generated by Django 2.2.2 on 2019-07-09 14:56

from django.db import migrations, models
import fit.utils
import fit.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0012_auto_20190705_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to=fit.utils.unique_file_path, validators=[fit.validators.ValidateFileType]),
        ),
    ]
