# Generated by Django 2.2.2 on 2019-07-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0013_auto_20190709_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='user_filename',
        ),
    ]
