# Generated by Django 2.2.2 on 2019-07-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0014_remove_upload_user_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
