# Generated by Django 2.2.2 on 2019-07-10 13:29

from django.db import migrations, models
import fit.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0015_assay'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='test_field',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assay',
            name='plot',
            field=models.ImageField(upload_to=fit.utils.unique_file_path),
        ),
    ]
