# Generated by Django 2.2.2 on 2019-07-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0016_auto_20190710_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assay',
            name='test_field',
        ),
        migrations.AddField(
            model_name='upload',
            name='user_filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
