# Generated by Django 2.2.2 on 2019-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0017_auto_20190710_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='user_filename',
            field=models.CharField(default='', max_length=2),
        ),
    ]
