# Generated by Django 2.2.2 on 2019-07-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0018_auto_20190710_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='user_filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
