# Generated by Django 2.2.2 on 2019-07-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('fit', '0020_remove_upload_user_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='session',
            field=models.ForeignKey(default='tfzs3e7d6x13029nvi88p9z7rhwwurcq', on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
