# Generated by Django 2.2.2 on 2019-07-23 16:15

import django.core.validators
from django.db import migrations, models
import fit.utils
import fit.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0021_assay_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='measurement_time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(max_length=255, upload_to=fit.utils.unique_file_path, validators=[fit.validators.ValidateFileType]),
        ),
    ]
