# Generated by Django 2.2.2 on 2019-07-23 16:23

from django.db import migrations, models
import fit.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0022_auto_20190723_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='plot',
            field=models.ImageField(max_length=255, upload_to=fit.utils.unique_file_path),
        ),
    ]
