# Generated by Django 2.2.2 on 2019-07-24 08:22

import django.core.validators
from django.db import migrations, models
import fit.utils
import fit.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0023_auto_20190723_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(max_length=255, upload_to=fit.utils.unique_file_path, validators=[django.core.validators.FileExtensionValidator(['csv']), fit.validators.ValidateFileType]),
        ),
    ]
