# Generated by Django 2.2.5 on 2019-09-03 10:10

from django.db import migrations, models
import fit.utils
import fit.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0024_auto_20190724_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(max_length=255, upload_to=fit.utils.unique_file_path, validators=[fit.validators.ValidateCsv]),
        ),
    ]
