# Generated by Django 2.2.5 on 2019-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0025_auto_20190903_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='run_time',
            field=models.FloatField(null=True),
        ),
    ]
