# Generated by Django 2.2.5 on 2019-09-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0027_assay_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assay',
            old_name='results',
            new_name='calculation_results',
        ),
    ]
