# Generated by Django 2.2.5 on 2019-09-04 14:00

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0028_auto_20190904_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='date_calculated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assay',
            name='experimental_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
