# Generated by Django 2.2.5 on 2019-09-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0029_auto_20190904_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedExperiment',
            fields=[
                ('assay_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fit.Assay')),
                ('date_shared', models.DateTimeField(auto_now_add=True)),
                ('sharing_id', models.CharField(max_length=255)),
            ],
            bases=('fit.assay',),
        ),
    ]
