# Generated by Django 2.2.5 on 2019-09-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0030_sharedexperiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedexperiment',
            old_name='sharing_id',
            new_name='share_id',
        ),
    ]
